//! The linked ticket, on disk. A worktree can be linked to a GitHub issue or PR (New Session links the
//! picked issue; `wtd ticket link` links anything). `sync` renders it — and every PR related to it (the
//! PRs that close the issue, plus the PR for the worktree's branch) with their reviews and inline
//! review threads (`file:line`, diff hunk, resolved/outdated) — to `<worktree>/.claude-ticket.md`, so
//! the agent reads that file instead of querying GitHub. With no explicit link, the branch's PR alone
//! is used. The daemon re-syncs live worktrees every few minutes; the file is git-ignored.
//!
//!   wtd ticket link <slug>/<name> <url | owner/repo#N | #N>
//!   wtd ticket unlink <slug>/<name>
//!   wtd ticket sync [<slug>/<name> | --all]
//!   wtd ticket show <slug>/<name>               → { link, path, exists }

use std::path::Path;

use anyhow::{bail, Context, Result};
use serde_json::{json, Value};

use crate::settings::{gh_json, out};
use crate::{gitx, paths, wt};

pub const FILE: &str = ".claude-ticket.md";
const HEADER: &str = "<!-- generated by worktree-dev (wtd ticket sync) — edits are overwritten -->";

fn key(id: &str) -> String {
    id.replace('/', "__")
}

/// `{repo: "owner/name", number}` for a worktree, if linked.
pub fn link_of(dev: &Path, id: &str) -> Option<Value> {
    wt::read_state(dev, "tickets", &key(id)).and_then(|t| serde_json::from_str(&t).ok())
}

/// `https://github.com/o/n/issues/12`, `…/pull/12`, `o/n#12`, `#12` / `12` (the repo's own GitHub).
pub fn parse_spec(dev: &Path, slug: &str, spec: &str) -> Result<(String, u64)> {
    let s = spec.trim();
    if let Some(rest) = s.strip_prefix("https://github.com/").or_else(|| s.strip_prefix("http://github.com/")) {
        let p: Vec<&str> = rest.trim_end_matches('/').split('/').collect();
        if p.len() >= 4 && (p[2] == "issues" || p[2] == "pull") {
            return Ok((format!("{}/{}", p[0], p[1]), p[3].split(['#', '?']).next().unwrap_or("").parse().context("bad issue number in URL")?));
        }
        bail!("not an issue or PR URL: {s}");
    }
    if let Some((repo, n)) = s.split_once('#') {
        let repo = if repo.is_empty() {
            crate::repos::github_repo(dev, slug).with_context(|| format!("'{slug}' isn't linked to a GitHub repo — use owner/repo#N"))?
        } else {
            repo.to_string()
        };
        if repo.split('/').count() != 2 {
            bail!("repo must look like owner/name");
        }
        return Ok((repo, n.trim().parse().context("bad issue number")?));
    }
    let n: u64 = s.parse().context("expected a URL, owner/repo#N or #N")?;
    Ok((crate::repos::github_repo(dev, slug).with_context(|| format!("'{slug}' isn't linked to a GitHub repo — use owner/repo#N"))?, n))
}

pub fn link(dev: &Path, id: &str, repo: &str, number: u64) -> Result<()> {
    wt::write_state(dev, "tickets", &key(id), &json!({ "repo": repo, "number": number }).to_string())
}

fn graphql(query: &str, vars: &[(&str, String)]) -> Result<Value> {
    let mut args: Vec<String> = vec!["api".into(), "graphql".into(), "-f".into(), format!("query={query}")];
    for (k, v) in vars {
        let typed = v.parse::<u64>().is_ok() && *k == "number";
        args.push(if typed { "-F".into() } else { "-f".into() });
        args.push(format!("{k}={v}"));
    }
    let refs: Vec<&str> = args.iter().map(String::as_str).collect();
    let v = gh_json(&refs)?;
    if let Some(e) = v.get("errors").and_then(Value::as_array).and_then(|a| a.first()) {
        bail!("GitHub: {}", e.get("message").and_then(Value::as_str).unwrap_or("query failed"));
    }
    Ok(v.get("data").cloned().unwrap_or(Value::Null))
}

const Q_ITEM: &str = "query($owner:String!,$name:String!,$number:Int!){repository(owner:$owner,name:$name){issueOrPullRequest(number:$number){__typename
... on Issue{number title state url body createdAt author{login} assignees(first:10){nodes{login}} labels(first:20){nodes{name}}
 comments(last:50){nodes{author{login} createdAt body}} closedByPullRequestsReferences(first:5,includeClosedPrs:true){nodes{number}}}
... on PullRequest{number}}}}";
const Q_PR: &str = "query($owner:String!,$name:String!,$number:Int!){repository(owner:$owner,name:$name){pullRequest(number:$number){
number title state isDraft url body headRefName baseRefName reviewDecision author{login} labels(first:20){nodes{name}}
comments(last:40){nodes{author{login} createdAt body}}
reviews(last:40){nodes{author{login} state submittedAt body}}
reviewThreads(first:100){nodes{isResolved isOutdated path line originalLine comments(first:40){nodes{author{login} createdAt body diffHunk}}}}}}}";
const Q_BRANCH: &str = "query($owner:String!,$name:String!,$branch:String!){repository(owner:$owner,name:$name){
pullRequests(headRefName:$branch,first:3,orderBy:{field:CREATED_AT,direction:DESC}){nodes{number}}}}";

fn s<'a>(v: &'a Value, p: &str) -> &'a str {
    v.pointer(p).and_then(Value::as_str).unwrap_or("")
}
fn logins(v: &Value, p: &str, k: &str) -> Vec<String> {
    v.pointer(p).and_then(Value::as_array).map(|a| a.iter().filter_map(|x| x.get(k).and_then(Value::as_str).map(String::from)).collect()).unwrap_or_default()
}
fn day(ts: &str) -> &str {
    ts.get(..10).unwrap_or(ts)
}
fn quote(body: &str) -> String {
    let b = body.trim();
    if b.is_empty() { "> _(no text)_".into() } else { b.lines().map(|l| format!("> {l}")).collect::<Vec<_>>().join("\n") }
}

fn render_comments(md: &mut String, v: &Value, p: &str, title: &str) {
    let Some(cs) = v.pointer(p).and_then(Value::as_array).filter(|a| !a.is_empty()) else { return };
    md.push_str(&format!("\n### {title} ({})\n", cs.len()));
    for c in cs {
        md.push_str(&format!("\n**@{}** · {}\n\n{}\n", s(c, "/author/login"), day(s(c, "/createdAt")), quote(s(c, "/body"))));
    }
}

fn render_pr(md: &mut String, pr: &Value, why: &str) {
    let state = if pr.get("isDraft").and_then(Value::as_bool) == Some(true) { "DRAFT".to_string() } else { s(pr, "/state").to_string() };
    md.push_str(&format!("\n## Pull request #{} — {}\n\n", pr["number"], s(pr, "/title")));
    md.push_str(&format!("- {state} · `{}` → `{}` · by @{} · {why}\n", s(pr, "/headRefName"), s(pr, "/baseRefName"), s(pr, "/author/login")));
    let decision = s(pr, "/reviewDecision");
    if !decision.is_empty() {
        md.push_str(&format!("- Review decision: **{decision}**\n"));
    }
    md.push_str(&format!("- {}\n", s(pr, "/url")));
    let body = s(pr, "/body").trim();
    if !body.is_empty() {
        md.push_str(&format!("\n### PR description\n\n{body}\n"));
    }
    if let Some(rs) = pr.pointer("/reviews/nodes").and_then(Value::as_array) {
        let rs: Vec<&Value> = rs.iter().filter(|r| !s(r, "/body").trim().is_empty() || s(r, "/state") != "COMMENTED").collect();
        if !rs.is_empty() {
            md.push_str(&format!("\n### Reviews ({})\n", rs.len()));
            for r in rs {
                md.push_str(&format!("\n**@{}** — {} · {}\n", s(r, "/author/login"), s(r, "/state"), day(s(r, "/submittedAt"))));
                if !s(r, "/body").trim().is_empty() {
                    md.push_str(&format!("\n{}\n", quote(s(r, "/body"))));
                }
            }
        }
    }
    if let Some(ts) = pr.pointer("/reviewThreads/nodes").and_then(Value::as_array).filter(|a| !a.is_empty()) {
        let open = ts.iter().filter(|t| t.get("isResolved").and_then(Value::as_bool) != Some(true)).count();
        md.push_str(&format!("\n## Review comments ({} thread(s), {open} unresolved)\n", ts.len()));
        // unresolved first, then by file
        let mut ts: Vec<&Value> = ts.iter().collect();
        ts.sort_by_key(|t| (t.get("isResolved").and_then(Value::as_bool) == Some(true), s(t, "/path").to_string()));
        for t in ts {
            let line = t.get("line").and_then(Value::as_u64).or_else(|| t.get("originalLine").and_then(Value::as_u64)).map(|n| format!(":{n}")).unwrap_or_default();
            let mut flags = vec![];
            if t.get("isResolved").and_then(Value::as_bool) == Some(true) { flags.push("resolved"); } else { flags.push("**unresolved**"); }
            if t.get("isOutdated").and_then(Value::as_bool) == Some(true) { flags.push("outdated"); }
            md.push_str(&format!("\n### `{}{line}` — {}\n", s(t, "/path"), flags.join(", ")));
            let cs = t.pointer("/comments/nodes").and_then(Value::as_array).cloned().unwrap_or_default();
            if let Some(h) = cs.first().map(|c| s(c, "/diffHunk")).filter(|h| !h.is_empty()) {
                let lines: Vec<&str> = h.lines().collect();
                let tail = &lines[lines.len().saturating_sub(12)..];
                md.push_str(&format!("\n```diff\n{}\n```\n", tail.join("\n")));
            }
            for c in &cs {
                md.push_str(&format!("\n**@{}** · {}\n\n{}\n", s(c, "/author/login"), day(s(c, "/createdAt")), quote(s(c, "/body"))));
            }
        }
    }
    render_comments(md, pr, "/comments/nodes", "PR conversation");
}

fn split(repo: &str) -> Result<(String, String)> {
    repo.split_once('/').map(|(a, b)| (a.to_string(), b.to_string())).context("repo must be owner/name")
}

/// Render the ticket markdown for a worktree; None = nothing linked and no PR for the branch.
pub fn render(dev: &Path, id: &str, wtp: &Path) -> Result<Option<String>> {
    let slug = id.split('/').next().unwrap_or("");
    let linked = link_of(dev, id);
    let repo = match &linked {
        Some(l) => l.get("repo").and_then(Value::as_str).unwrap_or("").to_string(),
        None => match crate::repos::github_repo(dev, slug) { Some(r) => r, None => return Ok(None) },
    };
    let (owner, name) = split(&repo)?;
    let base = |n: u64| vec![("owner", owner.clone()), ("name", name.clone()), ("number", n.to_string())];
    let mut md = String::new();
    let mut prs: Vec<(u64, String)> = vec![];
    if let Some(n) = linked.as_ref().and_then(|l| l.get("number")).and_then(Value::as_u64) {
        let item = graphql(Q_ITEM, &base(n))?;
        let it = item.pointer("/repository/issueOrPullRequest").cloned().unwrap_or(Value::Null);
        match s(&it, "/__typename") {
            "Issue" => {
                md.push_str(&format!("# #{n} {}\n\n", s(&it, "/title")));
                let mut meta = vec![format!("Issue · **{}**", s(&it, "/state")), format!("opened by @{} on {}", s(&it, "/author/login"), day(s(&it, "/createdAt")))];
                let a = logins(&it, "/assignees/nodes", "login");
                if !a.is_empty() { meta.push(format!("assignees: {}", a.iter().map(|x| format!("@{x}")).collect::<Vec<_>>().join(", "))); }
                let l = logins(&it, "/labels/nodes", "name");
                if !l.is_empty() { meta.push(format!("labels: {}", l.join(", "))); }
                md.push_str(&format!("- {}\n- {}\n", meta.join(" · "), s(&it, "/url")));
                let body = s(&it, "/body").trim();
                md.push_str(&format!("\n## Description\n\n{}\n", if body.is_empty() { "_(no description)_" } else { body }));
                render_comments(&mut md, &it, "/comments/nodes", "Comments");
                for p in it.pointer("/closedByPullRequestsReferences/nodes").and_then(Value::as_array).into_iter().flatten() {
                    if let Some(pn) = p.get("number").and_then(Value::as_u64) {
                        prs.push((pn, "closes this issue".into()));
                    }
                }
            }
            "PullRequest" => prs.push((n, "the linked PR".into())),
            _ => bail!("{repo}#{n} not found (or no access)"),
        }
    }
    // the PR for this worktree's branch, linked or not
    if let Ok(branch) = gitx::out(&["-C", &gitx::s(wtp), "rev-parse", "--abbrev-ref", "HEAD"]) {
        if branch != "HEAD" {
            let r = graphql(Q_BRANCH, &[("owner", owner.clone()), ("name", name.clone()), ("branch", branch.clone())])?;
            for p in r.pointer("/repository/pullRequests/nodes").and_then(Value::as_array).into_iter().flatten() {
                if let Some(pn) = p.get("number").and_then(Value::as_u64) {
                    if !prs.iter().any(|(x, _)| *x == pn) {
                        prs.push((pn, format!("opened from this branch (`{branch}`)")));
                    }
                }
            }
        }
    }
    if linked.is_none() && prs.is_empty() {
        return Ok(None);
    }
    if linked.is_none() {
        md.push_str("# Pull request for this branch\n");
    }
    for (pn, why) in &prs {
        let r = graphql(Q_PR, &base(*pn))?;
        if let Some(pr) = r.pointer("/repository/pullRequest").filter(|v| !v.is_null()) {
            render_pr(&mut md, pr, why);
        }
    }
    Ok(Some(md))
}

/// Re-render and write `.claude-ticket.md` when its content changed. → whether a file was written.
pub fn sync(dev: &Path, id: &str) -> Result<bool> {
    let wtp = paths::worktree_path(dev, id);
    if !wtp.is_dir() {
        bail!("no worktree '{id}'");
    }
    let path = wtp.join(FILE);
    let old = std::fs::read_to_string(&path).unwrap_or_default();
    let strip = |t: &str| t.lines().filter(|l| !l.starts_with("_Synced ")).collect::<Vec<_>>().join("\n");
    match render(dev, id, &wtp)? {
        Some(md) => {
            let now = crate::daemon::fmt_local(std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).map(|d| d.as_secs() as i64).unwrap_or(0));
            let text = format!("{HEADER}\n_Synced {now} — read this instead of querying GitHub; `wtd ticket sync` refreshes it._\n\n{}", md.trim_start());
            if strip(&text) == strip(&old) {
                return Ok(false);
            }
            std::fs::write(&path, text)?;
            Ok(true)
        }
        None => {
            if old.starts_with(HEADER) {
                let _ = std::fs::remove_file(&path); // was ours; nothing linked any more
            }
            Ok(false)
        }
    }
}

pub fn main(args: &[String]) -> Result<i32> {
    let dev = paths::dev_root()?;
    let a: Vec<&str> = args.iter().map(String::as_str).collect();
    let here = || -> Result<String> {
        paths::resolve_worktree(&dev, &std::env::current_dir()?).filter(|r| r.id != wtd_core::model::DEV_ID).map(|r| r.id).context("not inside a worktree (pass <slug>/<name>)")
    };
    match a.as_slice() {
        ["link", id, spec] => {
            let slug = id.split('/').next().unwrap_or("");
            let (repo, n) = parse_spec(&dev, slug, spec)?;
            link(&dev, id, &repo, n)?;
            let wrote = sync(&dev, id).unwrap_or_else(|e| { eprintln!("linked, but the first sync failed: {e:#}"); false });
            out(json!({ "ok": true, "repo": repo, "number": n, "written": wrote }))?;
            Ok(0)
        }
        ["unlink", id] => {
            wt::forget_state(&dev, "tickets", &key(id));
            let _ = sync(&dev, id);
            out(json!({ "ok": true }))?;
            Ok(0)
        }
        ["sync", "--all"] => {
            let mut n = 0;
            for w in crate::daemon::scan::scan(&dev).into_iter().filter(|w| w.id != wtd_core::model::DEV_ID) {
                match sync(&dev, &w.id) {
                    Ok(true) => { n += 1; println!("updated {}", w.id); }
                    Ok(false) => {}
                    Err(e) => eprintln!("{}: {e:#}", w.id),
                }
            }
            println!("{n} ticket file(s) updated");
            Ok(0)
        }
        ["sync"] | ["sync", _] => {
            let id = match a.get(1) { Some(i) => i.to_string(), None => here()? };
            let wrote = sync(&dev, &id)?;
            let exists = paths::worktree_path(&dev, &id).join(FILE).is_file();
            println!("{}", if !exists { format!("{id}: nothing linked and no PR for this branch") } else if wrote { format!("{id}: {FILE} updated") } else { format!("{id}: {FILE} already current") });
            Ok(0)
        }
        ["show"] | ["show", _] => {
            let id = match a.get(1) { Some(i) => i.to_string(), None => here()? };
            let p = paths::worktree_path(&dev, &id).join(FILE);
            out(json!({ "link": link_of(&dev, &id), "path": p.to_string_lossy(), "exists": p.is_file() }))?;
            Ok(0)
        }
        _ => bail!("usage: wtd ticket link <slug>/<name> <url|owner/repo#N|#N> | unlink <slug>/<name> | sync [<slug>/<name>|--all] | show [<slug>/<name>]"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_urls_and_refs() {
        let dev = std::env::temp_dir();
        assert_eq!(parse_spec(&dev, "x", "https://github.com/o/n/issues/12").unwrap(), ("o/n".into(), 12));
        assert_eq!(parse_spec(&dev, "x", "https://github.com/o/n/pull/7#discussion_r1").unwrap(), ("o/n".into(), 7));
        assert_eq!(parse_spec(&dev, "x", "o/n#3").unwrap(), ("o/n".into(), 3));
        assert!(parse_spec(&dev, "x", "https://github.com/o/n").is_err());
    }
}
